In [51]:
import pandas as pd
corp_info = pd.read_csv('corp.csv', header=0, encoding='cp949')
# corp_info = corp_info[['종목코드','종목명','현재가','상장주식수']]
corp_info = corp_info[['종목코드','종목명','종가','상장주식수']]

items = []
for item in corp_info['종목코드']:
    item  = format(item, '06')
    items.append(item)
    
corp_info['종목코드'] = items
corp_info['종목코드'] = 'A' + corp_info['종목코드'].apply(str)

corp_info

       종목코드         종목명       종가       상장주식수
0   A005930        삼성전자    79000  5969782550
1   A000660      SK하이닉스   119000   728002365
2   A035420       NAVER   443000   164263395
3   A035720         카카오   154000   444460230
4   A207940    삼성바이오로직스   916000    66165000
5   A005935       삼성전자우    72500   822886700
6   A051910        LG화학   820000    70592343
7   A006400       삼성SDI   743000    68764530
8   A005380         현대차   227500   213668187
9   A068270        셀트리온   263000   137916534
10  A000270          기아    85800   405363347
11  A005490       POSCO   334500    87186835
12  A051900      LG생활건강  1711000    15618197
13  A012330       현대모비스   280000    94793094
14  A066570        LG전자   157500   163647814
15  A028260        삼성물산   132500   186887081
16  A096770     SK이노베이션   258000    92465564
17  A017670       SK텔레콤   326500    72060143
18  A105560        KB금융    51100   415807920
19  A055550        신한지주    38200   516599554
20  A034730          SK   273000    70360297
21  A036570       엔씨소프트   827000    21954022
22  A011200         HMM    43900   405392487
23  A091990    셀트리온헬스케어   112300   154990922
24  A015760        한국전력    25650   641964077
25  A003550          LG    97000   157300993
26  A032830        삼성생명    76000   200000000
27  A361610  SK아이이테크놀로지   211000    71297592
28  A018260     삼성에스디에스   183500    77377800
29  A090430      아모레퍼시픽   240500    58458490
30  A009150        삼성전기   184000    74693696
31  A003670      포스코케미칼   166500    77463220
32  A086790      하나금융지주    42800   300242062
33  A352820         하이브   315000    39002817
34  A302440   SK바이오사이언스   156500    76500000
35  A251270         넷마블   137500    85953502
36  A033780        KT&G    83300   137292497
37  A010950       S-Oil    97400   112582792
38  A034020       두산중공업    24800   427675765
39  A003490        대한항공    30350   347820825
40  A000810        삼성화재   218000    47374837
41  A326030      SK바이오팜   125500    78313250
42  A011170       롯데케미칼   273500    34275419
43  A010130        고려아연   473000    18870000
44  A030200          KT    33350   261111808
45  A009540      한국조선해양   123000    70773116
46  A018880       한온시스템    15950   533800000
47  A316140      우리금융지주    11300   722267683
48  A034220     LG디스플레이    22800   357815700
49  A009830       한화솔루션    42250   191278497

In [53]:
corp_result = pd.read_excel('SAMPLE_2018.xlsx')
corp_result

,종목코드,회사명,당기순이익,유동자산,부채총계,매출총이익,자본총계,자산총계
0,A000020,동화약품,10068113000,227887463000,73198591000,115903237000,297400652000,370599243000
1,A000040,KR모터스,-24442080000,86949763000,85006462000,-631020000,69894605000,154901067000
2,A000050,경방,20189241000,120711492000,593023494000,107395818000,708769347000,1301792841000
3,A000060,메리츠화재,234721346000,0,18195561629000,0,2283200522000,20478762151000
4,A000070,삼양홀딩스,102512252000,1057235344000,1311855275000,482105988000,2001941981000,3313797255000
...,...,...,...,...,...,...,...,...
2004,A311270,키움제5호스팩,-130749000,0,769275000,0,7103863000,7873138000
2005,A313750,유안타제4호스팩,-13122000,0,1103143000,0,685353000,1788497000
2006,A316140,우리금융지주,0,0,0,0,0,0
2007,A317030,케이비17호스팩,0,0,0,0,0,0
2008,A317320,한화에스비아이스팩,0,0,0,0,0,0

In [54]:
corp_data = corp_result[['종목코드','당기순이익']]
corp_data

         종목코드         당기순이익
0     A000020   10068113000
1     A000040  -24442080000
2     A000050   20189241000
3     A000060  234721346000
4     A000070  102512252000
...       ...           ...
2004  A311270    -130749000
2005  A313750     -13122000
2006  A316140             0
2007  A317030             0
2008  A317320             0

[2009 rows x 2 columns]

In [55]:
corp_total = pd.merge(corp_info, corp_data, how='left', on='종목코드')
corp_total

       종목코드         종목명       종가       상장주식수         당기순이익
0   A005930        삼성전자    79000  5969782550  4.434486e+13
1   A000660      SK하이닉스   119000   728002365  1.553998e+13
2   A035420       NAVER   443000   164263395  6.279019e+11
3   A035720         카카오   154000   444460230  1.588886e+10
4   A207940    삼성바이오로직스   916000    66165000  2.241092e+11
5   A005935       삼성전자우    72500   822886700           NaN
6   A051910        LG화학   820000    70592343  1.519312e+12
7   A006400       삼성SDI   743000    68764530  7.450492e+11
8   A005380         현대차   227500   213668187  1.645019e+12
9   A068270        셀트리온   263000   137916534  2.535631e+11
10  A000270          기아    85800   405363347  1.155943e+12
11  A005490       POSCO   334500    87186835  1.892064e+12
12  A051900      LG생활건강  1711000    15618197  6.922787e+11
13  A012330       현대모비스   280000    94793094  1.888206e+12
14  A066570        LG전자   157500   163647814  1.472814e+12
15  A028260        삼성물산   132500   186887081  1.748244e+12
16  A096770     SK이노베이션   258000    92465564  1.709984e+12
17  A017670       SK텔레콤   326500    72060143  3.131988e+12
18  A105560        KB금융    51100   415807920  3.061946e+12
19  A055550        신한지주    38200   516599554  3.198265e+12
20  A034730          SK   273000    70360297  6.151141e+12
21  A036570       엔씨소프트   827000    21954022  4.214677e+11
22  A011200         HMM    43900   405392487 -7.905630e+11
23  A091990    셀트리온헬스케어   112300   154990922  1.138614e+10
24  A015760        한국전력    25650   641964077 -1.174498e+12
25  A003550          LG    97000   157300993  1.882897e+12
26  A032830        삼성생명    76000   200000000  1.733710e+12
27  A361610  SK아이이테크놀로지   211000    71297592           NaN
28  A018260     삼성에스디에스   183500    77377800  6.387923e+11
29  A090430      아모레퍼시픽   240500    58458490  3.348446e+11
30  A009150        삼성전기   184000    74693696  6.850185e+11
31  A003670      포스코케미칼   166500    77463220  1.327520e+11
32  A086790      하나금융지주    42800   300242062  2.275152e+12
33  A352820         하이브   315000    39002817           NaN
34  A302440   SK바이오사이언스   156500    76500000           NaN
35  A251270         넷마블   137500    85953502  2.149321e+11
36  A033780        KT&G    83300   137292497  8.986593e+11
37  A010950       S-Oil    97400   112582792  2.580350e+11
38  A034020       두산중공업    24800   427675765 -4.217251e+11
39  A003490        대한항공    30350   347820825 -1.856514e+11
40  A000810        삼성화재   218000    47374837  1.073301e+12
41  A326030      SK바이오팜   125500    78313250           NaN
42  A011170       롯데케미칼   273500    34275419  1.641934e+12
43  A010130        고려아연   473000    18870000  5.348149e+11
44  A030200          KT    33350   261111808  7.623050e+11
45  A009540      한국조선해양   123000    70773116 -4.536102e+11
46  A018880       한온시스템    15950   533800000  2.836974e+11
47  A316140      우리금융지주    11300   722267683  0.000000e+00
48  A034220     LG디스플레이    22800   357815700 -1.794430e+11
49  A009830       한화솔루션    42250   191278497  1.604450e+11

In [77]:
corp_total["EPS"] = corp_total['당기순이익']/corp_total['상장주식수']
corp_total

,종목코드,종목명,종가,상장주식수,당기순이익,EPS,PER
0.0,A005930,삼성전자,79000.0,5.969783e+09,4.434486e+13,7428.219810,10.635119
1.0,A000660,SK하이닉스,119000.0,7.280024e+08,1.553998e+13,21346.062523,5.574799
2.0,A035420,NAVER,443000.0,1.642634e+08,6.279019e+11,3822.530717,115.891809
3.0,A035720,카카오,154000.0,4.444602e+08,1.588886e+10,35.748663,4307.853410
4.0,A207940,삼성바이오로직스,916000.0,6.616500e+07,2.241092e+11,3387.126049,270.435758
6.0,A051910,LG화학,820000.0,7.059234e+07,1.519312e+12,21522.334228,38.099957
7.0,A006400,삼성SDI,743000.0,6.876453e+07,7.450492e+11,10834.789171,68.575400
8.0,A005380,현대차,227500.0,2.136682e+08,1.645019e+12,7698.942098,29.549514
9.0,A068270,셀트리온,263000.0,1.379165e+08,2.535631e+11,1838.525836,143.049390
10.0,A000270,기아,85800.0,4.053633e+08,1.155943e+12,2851.621906,30.088140
11.0,A005490,POSCO,334500.0,8.718684e+07,1.892064e+12,21701.262650,15.413850
12.0,A051900,LG생활건강,1711000.0,1.561820e+07,6.922787e+11,44325.135994,38.601122
13.0,A012330,현대모비스,280000.0,9.479309e+07,1.888206e+12,19919.235889,14.056764
14.0,A066570,LG전자,157500.0,1.636478e+08,1.472814e+12,8999.900237,17.500194
15.0,A028260,삼성물산,132500.0,1.868871e+08,1.748244e+12,9354.544646,14.164238
16.0,A096770,SK이노베이션,258000.0,9.246556e+07,1.709984e+12,18493.198625,13.951075
17.0,A017670,SK텔레콤,326500.0,7.206014e+07,3.131988e+12,43463.527404,7.512046
18.0,A105560,KB금융,51100.0,4.158079e+08,3.061946e+12,7363.847230,6.939307
19.0,A055550,신한지주,38200.0,5.165996e+08,3.198265e+12,6190.994505,6.170253
20.0,A034730,SK,273000.0,7.036030e+07,6.151141e+12,87423.465538,3.122731
21.0,A036570,엔씨소프트,827000.0,2.195402e+07,4.214677e+11,19197.742036,43.077983
22.0,A011200,HMM,43900.0,4.053925e+08,-7.905630e+11,-1950.117541,-22.511464
23.0,A091990,셀트리온헬스케어,112300.0,1.549909e+08,1.138614e+10,73.463270,1528.655061
24.0,A015760,한국전력,25650.0,6.419641e+08,-1.174498e+12,-1829.538509,-14.019929
25.0,A003550,LG,97000.0,1.573010e+08,1.882897e+12,11970.026152,8.103575
26.0,A032830,삼성생명,76000.0,2.000000e+08,1.733710e+12,8668.550000,8.767326
28.0,A018260,삼성에스디에스,183500.0,7.737780e+07,6.387923e+11,8255.497804,22.227612
29.0,A090430,아모레퍼시픽,240500.0,5.845849e+07,3.348446e+11,5727.903064,41.987442
30.0,A009150,삼성전기,184000.0,7.469370e+07,6.850185e+11,9171.035183,20.063166
31.0,A003670,포스코케미칼,166500.0,7.746322e+07,1.327520e+11,1713.742909,97.155763
32.0,A086790,하나금융지주,42800.0,3.002421e+08,2.275152e+12,7577.725735,5.648133
35.0,A251270,넷마블,137500.0,8.595350e+07,2.149321e+11,2500.562548,54.987627
36.0,A033780,KT&G,83300.0,1.372925e+08,8.986593e+11,6545.582312,12.726140
37.0,A010950,S-Oil,97400.0,1.125828e+08,2.580350e+11,2291.957727,42.496421
38.0,A034020,두산중공업,24800.0,4.276758e+08,-4.217251e+11,-986.086065,-25.149935
39.0,A003490,대한항공,30350.0,3.478208e+08,-1.856514e+11,-533.755991,-56.861189
40.0,A000810,삼성화재,218000.0,4.737484e+07,1.073301e+12,22655.512419,9.622382
42.0,A011170,롯데케미칼,273500.0,3.427542e+07,1.641934e+12,47904.130304,5.709320
43.0,A010130,고려아연,473000.0,1.887000e+07,5.348149e+11,28342.074139,16.688969
44.0,A030200,KT,33350.0,2.611118e+08,7.623050e+11,2919.458166,11.423353
45.0,A009540,한국조선해양,123000.0,7.077312e+07,-4.536102e+11,-6409.358053,-19.190689
46.0,A018880,한온시스템,15950.0,5.338000e+08,2.836974e+11,531.467628,30.011235
47.0,A316140,우리금융지주,11300.0,7.222677e+08,0.000000e+00,0.000000,inf
48.0,A034220,LG디스플레이,22800.0,3.578157e+08,-1.794430e+11,-501.495602,-45.464008
49.0,A009830,한화솔루션,42250.0,1.912785e+08,1.604450e+11,838.803067,50.369391

In [71]:
corp_total = corp_total[ pd.notnull(corp_total['EPS']) ]
corp_total = corp_total[ pd.notnull(corp_total['종가']) ]
corp_total

         종목코드       종목명         종가         상장주식수         당기순이익           EPS
0.0   A005930      삼성전자    79000.0  5.969783e+09  4.434486e+13   7428.219810
1.0   A000660    SK하이닉스   119000.0  7.280024e+08  1.553998e+13  21346.062523
2.0   A035420     NAVER   443000.0  1.642634e+08  6.279019e+11   3822.530717
3.0   A035720       카카오   154000.0  4.444602e+08  1.588886e+10     35.748663
4.0   A207940  삼성바이오로직스   916000.0  6.616500e+07  2.241092e+11   3387.126049
6.0   A051910      LG화학   820000.0  7.059234e+07  1.519312e+12  21522.334228
7.0   A006400     삼성SDI   743000.0  6.876453e+07  7.450492e+11  10834.789171
8.0   A005380       현대차   227500.0  2.136682e+08  1.645019e+12   7698.942098
9.0   A068270      셀트리온   263000.0  1.379165e+08  2.535631e+11   1838.525836
10.0  A000270        기아    85800.0  4.053633e+08  1.155943e+12   2851.621906
11.0  A005490     POSCO   334500.0  8.718684e+07  1.892064e+12  21701.262650
12.0  A051900    LG생활건강  1711000.0  1.561820e+07  6.922787e+11  44325.135994
13.0  A012330     현대모비스   280000.0  9.479309e+07  1.888206e+12  19919.235889
14.0  A066570      LG전자   157500.0  1.636478e+08  1.472814e+12   8999.900237
15.0  A028260      삼성물산   132500.0  1.868871e+08  1.748244e+12   9354.544646
16.0  A096770   SK이노베이션   258000.0  9.246556e+07  1.709984e+12  18493.198625
17.0  A017670     SK텔레콤   326500.0  7.206014e+07  3.131988e+12  43463.527404
18.0  A105560      KB금융    51100.0  4.158079e+08  3.061946e+12   7363.847230
19.0  A055550      신한지주    38200.0  5.165996e+08  3.198265e+12   6190.994505
20.0  A034730        SK   273000.0  7.036030e+07  6.151141e+12  87423.465538
21.0  A036570     엔씨소프트   827000.0  2.195402e+07  4.214677e+11  19197.742036
22.0  A011200       HMM    43900.0  4.053925e+08 -7.905630e+11  -1950.117541
23.0  A091990  셀트리온헬스케어   112300.0  1.549909e+08  1.138614e+10     73.463270
24.0  A015760      한국전력    25650.0  6.419641e+08 -1.174498e+12  -1829.538509
25.0  A003550        LG    97000.0  1.573010e+08  1.882897e+12  11970.026152
26.0  A032830      삼성생명    76000.0  2.000000e+08  1.733710e+12   8668.550000
28.0  A018260   삼성에스디에스   183500.0  7.737780e+07  6.387923e+11   8255.497804
29.0  A090430    아모레퍼시픽   240500.0  5.845849e+07  3.348446e+11   5727.903064
30.0  A009150      삼성전기   184000.0  7.469370e+07  6.850185e+11   9171.035183
31.0  A003670    포스코케미칼   166500.0  7.746322e+07  1.327520e+11   1713.742909
32.0  A086790    하나금융지주    42800.0  3.002421e+08  2.275152e+12   7577.725735
35.0  A251270       넷마블   137500.0  8.595350e+07  2.149321e+11   2500.562548
36.0  A033780      KT&G    83300.0  1.372925e+08  8.986593e+11   6545.582312
37.0  A010950     S-Oil    97400.0  1.125828e+08  2.580350e+11   2291.957727
38.0  A034020     두산중공업    24800.0  4.276758e+08 -4.217251e+11   -986.086065
39.0  A003490      대한항공    30350.0  3.478208e+08 -1.856514e+11   -533.755991
40.0  A000810      삼성화재   218000.0  4.737484e+07  1.073301e+12  22655.512419
42.0  A011170     롯데케미칼   273500.0  3.427542e+07  1.641934e+12  47904.130304
43.0  A010130      고려아연   473000.0  1.887000e+07  5.348149e+11  28342.074139
44.0  A030200        KT    33350.0  2.611118e+08  7.623050e+11   2919.458166
45.0  A009540    한국조선해양   123000.0  7.077312e+07 -4.536102e+11  -6409.358053
46.0  A018880     한온시스템    15950.0  5.338000e+08  2.836974e+11    531.467628
47.0  A316140    우리금융지주    11300.0  7.222677e+08  0.000000e+00      0.000000
48.0  A034220   LG디스플레이    22800.0  3.578157e+08 -1.794430e+11   -501.495602
49.0  A009830     한화솔루션    42250.0  1.912785e+08  1.604450e+11    838.803067

In [76]:
corp_total["PER"] = corp_total["종가"]/corp_total["EPS"]
corp_total

,종목코드,종목명,종가,상장주식수,당기순이익,EPS,PER
0.0,A005930,삼성전자,79000.0,5.969783e+09,4.434486e+13,7428.219810,10.635119
1.0,A000660,SK하이닉스,119000.0,7.280024e+08,1.553998e+13,21346.062523,5.574799
2.0,A035420,NAVER,443000.0,1.642634e+08,6.279019e+11,3822.530717,115.891809
3.0,A035720,카카오,154000.0,4.444602e+08,1.588886e+10,35.748663,4307.853410
4.0,A207940,삼성바이오로직스,916000.0,6.616500e+07,2.241092e+11,3387.126049,270.435758
6.0,A051910,LG화학,820000.0,7.059234e+07,1.519312e+12,21522.334228,38.099957
7.0,A006400,삼성SDI,743000.0,6.876453e+07,7.450492e+11,10834.789171,68.575400
8.0,A005380,현대차,227500.0,2.136682e+08,1.645019e+12,7698.942098,29.549514
9.0,A068270,셀트리온,263000.0,1.379165e+08,2.535631e+11,1838.525836,143.049390
10.0,A000270,기아,85800.0,4.053633e+08,1.155943e+12,2851.621906,30.088140
11.0,A005490,POSCO,334500.0,8.718684e+07,1.892064e+12,21701.262650,15.413850
12.0,A051900,LG생활건강,1711000.0,1.561820e+07,6.922787e+11,44325.135994,38.601122
13.0,A012330,현대모비스,280000.0,9.479309e+07,1.888206e+12,19919.235889,14.056764
14.0,A066570,LG전자,157500.0,1.636478e+08,1.472814e+12,8999.900237,17.500194
15.0,A028260,삼성물산,132500.0,1.868871e+08,1.748244e+12,9354.544646,14.164238
16.0,A096770,SK이노베이션,258000.0,9.246556e+07,1.709984e+12,18493.198625,13.951075
17.0,A017670,SK텔레콤,326500.0,7.206014e+07,3.131988e+12,43463.527404,7.512046
18.0,A105560,KB금융,51100.0,4.158079e+08,3.061946e+12,7363.847230,6.939307
19.0,A055550,신한지주,38200.0,5.165996e+08,3.198265e+12,6190.994505,6.170253
20.0,A034730,SK,273000.0,7.036030e+07,6.151141e+12,87423.465538,3.122731
21.0,A036570,엔씨소프트,827000.0,2.195402e+07,4.214677e+11,19197.742036,43.077983
22.0,A011200,HMM,43900.0,4.053925e+08,-7.905630e+11,-1950.117541,-22.511464
23.0,A091990,셀트리온헬스케어,112300.0,1.549909e+08,1.138614e+10,73.463270,1528.655061
24.0,A015760,한국전력,25650.0,6.419641e+08,-1.174498e+12,-1829.538509,-14.019929
25.0,A003550,LG,97000.0,1.573010e+08,1.882897e+12,11970.026152,8.103575
26.0,A032830,삼성생명,76000.0,2.000000e+08,1.733710e+12,8668.550000,8.767326
28.0,A018260,삼성에스디에스,183500.0,7.737780e+07,6.387923e+11,8255.497804,22.227612
29.0,A090430,아모레퍼시픽,240500.0,5.845849e+07,3.348446e+11,5727.903064,41.987442
30.0,A009150,삼성전기,184000.0,7.469370e+07,6.850185e+11,9171.035183,20.063166
31.0,A003670,포스코케미칼,166500.0,7.746322e+07,1.327520e+11,1713.742909,97.155763
32.0,A086790,하나금융지주,42800.0,3.002421e+08,2.275152e+12,7577.725735,5.648133
35.0,A251270,넷마블,137500.0,8.595350e+07,2.149321e+11,2500.562548,54.987627
36.0,A033780,KT&G,83300.0,1.372925e+08,8.986593e+11,6545.582312,12.726140
37.0,A010950,S-Oil,97400.0,1.125828e+08,2.580350e+11,2291.957727,42.496421
38.0,A034020,두산중공업,24800.0,4.276758e+08,-4.217251e+11,-986.086065,-25.149935
39.0,A003490,대한항공,30350.0,3.478208e+08,-1.856514e+11,-533.755991,-56.861189
40.0,A000810,삼성화재,218000.0,4.737484e+07,1.073301e+12,22655.512419,9.622382
42.0,A011170,롯데케미칼,273500.0,3.427542e+07,1.641934e+12,47904.130304,5.709320
43.0,A010130,고려아연,473000.0,1.887000e+07,5.348149e+11,28342.074139,16.688969
44.0,A030200,KT,33350.0,2.611118e+08,7.623050e+11,2919.458166,11.423353
45.0,A009540,한국조선해양,123000.0,7.077312e+07,-4.536102e+11,-6409.358053,-19.190689
46.0,A018880,한온시스템,15950.0,5.338000e+08,2.836974e+11,531.467628,30.011235
47.0,A316140,우리금융지주,11300.0,7.222677e+08,0.000000e+00,0.000000,inf
48.0,A034220,LG디스플레이,22800.0,3.578157e+08,-1.794430e+11,-501.495602,-45.464008
49.0,A009830,한화솔루션,42250.0,1.912785e+08,1.604450e+11,838.803067,50.369391

In [80]:
corp_filter = corp_total[(corp_total["PER"] >= 12) & (corp_total["PER"] <= 15)]
corp_filter

,종목코드,종목명,종가,상장주식수,당기순이익,EPS,PER
13.0,A012330,현대모비스,280000.0,94793094.0,1.888206e+12,19919.235889,14.056764
15.0,A028260,삼성물산,132500.0,186887081.0,1.748244e+12,9354.544646,14.164238
16.0,A096770,SK이노베이션,258000.0,92465564.0,1.709984e+12,18493.198625,13.951075
36.0,A033780,KT&G,83300.0,137292497.0,8.986593e+11,6545.582312,12.726140